### PR TITLE
Stop wrapping table cell contents with line breaks

### PR DESCRIPTION
**Pull request by Justineo**
A fix for remarkjs/remark-html#23.

### CODE REVIEW

**Comment by wooorm** [comment]
Sweet!

**Comment by Justineo** [comment]
Just asking, can you please release a new version on npm including this fix? Thanks :)

BTW, the build on Travis CI seems to be failing...

**Comment by wooorm** [comment]
Yeah I tried to run Travis three times yesterday, but they all failed installing, probably a bug somewhere in Travis? Anyway, This morning it worked and I was waiting on that 😉

Anyway, released!

**Comment by Justineo** [comment]
Great, thanks!

**Pull request merged**
