### PR TITLE
Wrap `footnote` definition in a paragraph

### PR DESCRIPTION
**Pull request by vhf**
Here is a fix for #14 

Please tell me what you think @wooorm !

### CODE REVIEW

**Comment by wooorm** [comment]
Hey hey! Sorry about the long wait!

This looks good for `text` elements, but I’m wondering about a single `strong`, or other non-block element. What would happen there?

In the reverse program, we have something similar:

https://github.com/syntax-tree/hast-util-to-mdast/blob/1c494735fea6eec3bfedaf28afccd5fc82022a5e/lib/wrap.js#L26-L57

Do you think that’s useful to add here too?

**Comment by vhf** [comment]
I'm pretty sure that would be better, yep.

Since I'll need the list inline nodes in here, it's not ideal to maintain IMO.

A few ideas/solutions:

1. creating a `mdast` package, only exporting nodes infos so that we could e.g. get a list of all inline nodes, or
1. exporting this from `remark`, or
1. attaching a type to each node besides the node type, e.g. `{type: 'emphasis', element: 'inline'}`

**Comment by wooorm** [comment]
Ahh, sorry, late!

I think a version of 1 makes the most sense, but in a separate utility? I think `mdast` should be used, if ever, for something like [`unist-builder`](https://github.com/eush77/unist-builder) but for mdast?

However, I think it makes sense to first inline it here, for now, before starting work on another utility?
Or, if it’s the same list as in `hast-util-to-mdast`, we could create a small utility and depend on it in both these projects?

**Comment by wooorm** [comment]
@vhf Ping! P.S. I know, I know, I’m horribly late all the time 😒

**Comment by vhf** [comment]
@wooorm I'm also constantly late, no worries. :)

It's the same list as `hast-util-to-mdast`. What would be a good package name?

**Comment by wooorm** [comment]
HTML doesn’t really have “block” or “inline”, as that’s related to CSS, but it does have [“phrasing” content](https://html.spec.whatwg.org/#kinds-of-content) (warning: the HTML spec is huge), which contains `<a>`, `<br>`, `<code>`, `<em>`, ``, `<s>`, `<strong>`, and `Text`.

So how about `mdast-util-phrasing`?

**Comment by vhf** [comment]
@wooorm Here's my suggestion: https://github.com/syntax-tree/mdast-util-phrasing

If you would have preferred I created this repo outside of the org then moved it there upon your approval please say so! :)

**Comment by wooorm** [comment]
No this is perfect! And what the organisation is for! Thank you!!! 🎉

So what are the next steps?

**Comment by vhf** [comment]
Next step would be to bump the `mdast-util-phrasing` to `1.0.0` and publish it to NPM, then I'd change this PR to leverage it and also I could also PR `hast-util-to-mdast` to remove the array checked [in here](https://github.com/syntax-tree/hast-util-to-mdast/blob/1c494735fea6eec3bfedaf28afccd5fc82022a5e/lib/wrap.js#L36).

**Comment by wooorm** [comment]
Sweet, sounds good! Could you add me on npm when you publish?

Would you like me to do something?

**Comment by vhf** [comment]
I will. No need, I can handle this. I'll assign the PR reviews to you. :)

**Comment by vhf** [comment]
All done.

- [x] 1.0.0 released
- [x] gave you access to the NPM package
- [ ] This PR is good to go, please merge or request modifications
- [ ] [hast-util-to-mdast PR is up for review](https://github.com/syntax-tree/hast-util-to-mdast/pull/33)

**Comment by wooorm** [comment]
Now that I look at this again, is there actually a need for checking if there’s one node, and it’s phrasing? If `footnote` is always inline, why not always wrap it in a paragraph?

**Comment by vhf** [comment]
`footnote` is not always inline:

```md
foo[^1]

[^1]: * foo
```

(There might be other examples in #14 )

**Comment by vhf** [comment]
I think you're right, `footnote` is always inline. (I deleted a comment I had just posted, I got confused with `footnote` and `footnoreReference`.)

**Comment by wooorm** [comment]
Right?! That’s what I was thinking as well! Oh, I’m so sorry for leading you astray with my first comment https://github.com/syntax-tree/mdast-util-to-hast/pull/15#issuecomment-332247980...

In that case, should we just wrap this in a `<p>`, always?

**Comment by vhf** [comment]
No big deal! Here it is again. 😄

**Comment by wooorm** [comment]
Sweet!

**Comment by wooorm** [comment]
Released, plus everything I can access that depends on it!

**Pull request closed without merging**
